### ISSUE TITLE
Setuptools 48 may be broken on Linux

### ISSUE THREAD

**Issue by pkgw** [conda-forge/setuptools-feedstock#153]
As suggested by the build failures on https://github.com/conda-forge/pillow-feedstock/pull/80 . Bog-standard Linux/x86_64 builds are failing with:

```
2020-07-03T17:08:55.0395186Z   cc -pthread -shared -Wl,-O2 ... -o build/lib.linux-x86_64-3.6/PIL/_imaging.pypy36-pp73-x86_64-linux-gnu.so
2020-07-03T17:08:55.0417062Z   error: [Errno 2] No such file or directory: 'cc': 'cc'
```

In that PR the Linux/ppc64le builds still pulled in setuptools 47 and succeeded. MacOS builds succeeded, Windows builds failed for a different reason.

**Comment by isuruf** [comment]
See also https://github.com/pypa/setuptools/blob/master/CHANGES.rst

**Comment by jakirkham** [comment]
We could mark 48 as broken.

**Comment by jakirkham** [comment]
Maybe the next release fixes it ( https://github.com/conda-forge/setuptools-feedstock/pull/154 )?

**Comment by jakirkham** [comment]
There's actually 2 Linux `x86_64` Python 3.6 builds?

<img width="1001" alt="Screen Shot 2020-07-03 at 3 42 41 PM" src="https://user-images.githubusercontent.com/3019665/86500121-d8718c00-bd43-11ea-8fdc-e35b02e195ad.png">

**Comment by pkgw** [comment]
Based on [the changelog](https://setuptools.readthedocs.io/en/latest/history.html#v49-1-0), looks like we may want to pull up to 49.1.0:

```
- #2228: Disabled distutils adoption for now while emergent issues are addressed.
```

**Comment by jakirkham** [comment]
Yeah that already went in ( https://github.com/conda-forge/setuptools-feedstock/pull/155 ).

**Comment by pkgw** [comment]
Seeing as 49.1 brings us back to the status quo, I'll go ahead and close this. I'm not really familiar with the mark-broken infrastructure but we may want to mark 48 and 49.0 as, well, broken.
