### ISSUE TITLE
Loading conda-specific _sysconfigdata is broken with >=50.0.0

### ISSUE THREAD

**Issue by mbargull** [conda-forge/setuptools-feedstock#168]
ref: https://github.com/conda-forge/admin-requests/pull/120

**Comment by jjhelmus** [comment]
I think porting the patches in the made to distutils in the python recipe to this feedstock will be sufficient to fix this issue.

**Comment by sarthakpati** [comment]
Hi admins,

Any update on this?

**Comment by isuruf** [comment]
I don't think anyone is working on this. PRs are welcome to port the patches from python-feedstock to here.

**Comment by isuruf** [comment]
Fixed now
