### ISSUE TITLE
Python 3 packages missing __pycache__ have .pyc

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/setuptools-feedstock#18]
Appears that the Python 3 packages built here do not have `__pycache__` directories as they would during a normal Python install. Instead they appear to have `.pyc` files as if they were Python 2 installs. Have confirmed this is not an issue with `setuptools` itself and that this is unique to the `conda-build` process.

xref: https://github.com/conda-forge/conda-smithy/issues/289

**Comment by jakirkham** [comment]
Am seeing this with other packages too. This is not unique to the `setuptools` package.

**Comment by jakirkham** [comment]
Elevated as issue ( https://github.com/conda-forge/setuptools-feedstock/issues/18 ).

**Comment by jjhelmus** [comment]
This is a known issue with `conda-build` 1.21.14 and 2.0.0 which has been fixed in `conda-build` 2.0.1.  See conda-forge/python-feedstock#70

**Comment by jakirkham** [comment]
This appears to be fixed by recent builds.
