### ISSUE TITLE
setuptools <58 for py310

### ISSUE THREAD

**Issue by bollwyvl** [conda-forge/setuptools-feedstock#205]
It looks like `keepalive` still uses `use_2to3`, which was finally removed in the `58.x` line of `setuptools`. Pinning to `<58` gets an `unsatsifiable` error.

https://github.com/conda-forge/keepalive-feedstock/pull/13#issuecomment-957552590

The usptream `keepalive`, which hasn't been updated in a few years, is a dependency of [sparqlwrapper](https://github.com/conda-forge/sparqlwrapper-feedstock/blob/fe1129723d44c8031ffb8dd108bf81fabe95dbcd/recipe/meta.yaml#L24) ([WIP feedstock PR](https://github.com/conda-forge/sparqlwrapper-feedstock/pull/20)) and therefore `rdflib`, so we need to figure out _something_, or that whole ecosystem will stay blocked... though I'm doing some investigation there (will report back).

I don't know how wide-spread `use_2to3` is, but as there's at least one other, I guess we could start a branch with ABI backports? The simplest play for `keepalive` would be `57.x`, but maybe before the big change which corresponds to the window of missing releases?

**Comment by isuruf** [comment]
> The simplest play for keepalive would be 57.x

No. Simplest way would be to run `2to3` manually.

**Comment by bollwyvl** [comment]
> run 2to3 manually.

interesting! are there any examples of this?

**Comment by isuruf** [comment]
https://github.com/conda-forge/adios-feedstock/blob/9ed76f9305a954ab48ea5a1f38e253acf5f6c59f/recipe/build.sh#L9-L13

**Comment by bollwyvl** [comment]
Will close for now!
