### ISSUE TITLE
We may need to pull the releases of setuptools 58.5.x

### ISSUE THREAD

**Issue by mariusvniekerk** [conda-forge/setuptools-feedstock#208]
https://github.com/pypa/setuptools/issues/2849

**Comment by jakirkham** [comment]
Thanks for info. Is there a PR to mark these `broken`?

**Comment by jakirkham** [comment]
Looks like this was fixed in 58.5.3 ( https://github.com/pypa/setuptools/pull/2855 ), which is now publishing ( https://github.com/conda-forge/setuptools-feedstock/pull/209 )

**Comment by h-vetinari** [comment]
Thanks for handling this so quickly!

**Comment by jakirkham** [comment]
We can still pull these if we want, but at this point new versions have superseded this broken one. Going to go ahead and close as resolved.
