### ISSUE TITLE
BUG: missing dependency on `backports.tarfile` on py38

### ISSUE THREAD

**Issue by h-vetinari** [conda-forge/setuptools-feedstock#351]
With
```
    python:                               3.8.19-hd12c33a_0_cpython      conda-forge
    [...]
    setuptools:                           71.0.4-pyhd8ed1ab_0            conda-forge
```
I'm getting
```
----------------------------- Captured stderr call -----------------------------
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from setuptools import setup
  File "$PREFIX/lib/python3.8/site-packages/setuptools/__init__.py", line 21, in <module>
    from .dist import Distribution
  File "$PREFIX/lib/python3.8/site-packages/setuptools/dist.py", line 29, in <module>
    from . import _entry_points
  File "$PREFIX/lib/python3.8/site-packages/setuptools/_entry_points.py", line 6, in <module>
    from jaraco.text import yield_lines
  File "$PREFIX/lib/python3.8/site-packages/setuptools/_vendor/jaraco/text/__init__.py", line 12, in <module>
    from jaraco.context import ExceptionTrap
  File "$PREFIX/lib/python3.8/site-packages/setuptools/_vendor/jaraco/context.py", line 17, in <module>
    from backports import tarfile
ImportError: cannot import name 'tarfile' from 'backports' ($PREFIX/lib/python3.8/site-packages/backports/__init__.py)
```

**Comment by rgommers** [comment]
I assume this only happens in some setups where the `backports` namespace package is installed for some other reason?

**Comment by h-vetinari** [comment]
> I assume this only happens in some setups where the `backports` namespace package is installed for some other reason?

No, AFAICT the issue is that the vendored `jaraco.{text,context}` depend on `backports.tarfile`, which itself _isn't_ vendored though, so this necessarily fails on py38 (well, unless something else assures the presence of `backports.tarfile` in the environment).

**Comment by rgommers** [comment]
That's not correct, it is vendored: https://github.com/pypa/setuptools/tree/main/setuptools/_vendor/backports/tarfile. The discussion on gh-352 points towards the better fix for that.

**Comment by travishathaway** [comment]
xref: https://github.com/conda/conda/issues/14078

**Comment by glatterf42** [comment]
Crosslinking the original issue with even more information: pypa/setuptools#4508

**Comment by Avasam** [comment]
Also crosslinking https://github.com/jaraco/jaraco.text/pull/15 which could sidestep the vendoring issue entirely.

**Comment by h-vetinari** [comment]
> Crosslinking the original issue with even more information: https://github.com/pypa/setuptools/issues/4508

This isn't even the original issue, but already the second iteration, where the workaround used to fixed the first doesn't work (yet) for conda-forge. It's upstream's prerogative to decline https://github.com/jaraco/jaraco.text/pull/15, but we should provide a working solution, and from where I stand, it really doesn't matter if it ends up using the vendored backports.tarfile, or one we shim it in as a regular dependency.

**Comment by h-vetinari** [comment]
This should have been closed by https://github.com/conda-forge/backports-feedstock/pull/7 🤞
