### ISSUE TITLE
setuptools version 34.0.1

### ISSUE THREAD

**Issue by jjhelmus** [conda-forge/setuptools-feedstock#57]
setuptools version `34.0.1` has been released and is [available on PyPI](https://pypi.python.org/pypi/setuptools).  There was a change to the `bootstrap.py` script which introduced a dependency on `pip`.  This causes a circular dependency which is causing issues, see #55.  

Reported the issue to upstream in pypa/setuptools#950

**Comment by jjhelmus** [comment]
Also see [release notice for setuptools 34.0.0](https://github.com/pypa/setuptools/blob/master/CHANGES.rst#v3400) for details on this change and recommendations.

**Comment by jakirkham** [comment]
As of 36.0.0, this is no longer necessary as `setuptools` has revendored its dependencies. 

xref: https://github.com/pypa/setuptools/issues/980

**Comment by Juanlu001** [comment]
I read most of pypa/setuptools#980 and tried to give this a go, but I get this error:

```
$ conda build recipe/
Attempting to finalize metadata for setuptools
INFO:conda_build.metadata:Attempting to finalize metadata for setuptools
setuptools cannot depend on itself
```

with this diff:

```
$ git diff
diff --git a/recipe/meta.yaml b/recipe/meta.yaml
index c38c8f4..99a3222 100644
--- a/recipe/meta.yaml
+++ b/recipe/meta.yaml
@@ -1,4 +1,4 @@
-{% set version = "33.1.1" %}
+{% set version = "36.2.0" %}
 
 package:
   name: setuptools
```

(notice I didn't even change the hash)

What do you think it's the problem here?

**Comment by jakirkham** [comment]
Probably some caching issue.

**Comment by jakirkham** [comment]
Closing as this has been resolved.
